name: "build docker image"

on: 
  workflow_dispatch:
    inputs:
      project:
        description: 'Project:VERSION'
        required: true
        default: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Set tag
        id: tag
        run: |
          echo "${{ github.event.inputs.project }}" > Project_VERSION
          if [[ -n $(awk -F: '{if($2)print $2}' Project_VERSION) ]]; then
            VERSION=$( awk -F: '{if($2)print $2}' Project_VERSION )
            PROJECT=$( awk -F: '{if($1)print $1}' Project_VERSION )
            echo "tag=$VERSION" >> $GITHUB_ENV
            echo "project=$PROJECT" >> $GITHUB_ENV
          else
            echo "tag=$(date +%Y)-$(date +%m)-$(date +%d)" >> $GITHUB_ENV
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ env.tag }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.project }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.project }}:${{ env.tag }}